import ArrowBackIos from '@mui/icons-material/ArrowBackIos';
import ArrowDropDown from '@mui/icons-material/ArrowDropDown';
import ArrowDropUp from '@mui/icons-material/ArrowDropUp';
import Cached from '@mui/icons-material/Cached';
import CheckCircle from '@mui/icons-material/CheckCircle';
import CheckCircleOutlined from '@mui/icons-material/CheckCircleOutlined';
import Clear from '@mui/icons-material/Clear';
import Close from '@mui/icons-material/Close';
import FilterList from '@mui/icons-material/FilterList';
import InfoOutlined from '@mui/icons-material/InfoOutlined';
import PlayArrow from '@mui/icons-material/PlayArrow';
import Search from '@mui/icons-material/Search';
import SkipNext from '@mui/icons-material/SkipNext';
import SortByAlpha from '@mui/icons-material/SortByAlpha';
export const icons = {ArrowBackIos, ArrowDropDown, ArrowDropUp, Cached, CheckCircle, CheckCircleOutlined, Clear, Close, FilterList, InfoOutlined, PlayArrow, Search, SkipNext, SortByAlpha};
